### ISSUE TITLE
Alternate social icons aren't round

### ISSUE THREAD

**Issue by ascott1** [cfpb/cf-icons#11]
As discussed in issues #4 and #8, we changed the alternate icon suffix from `-alt` to `-round`, but the alternate social icons are actually squares.

Should we...
1. Just use `round` anyway
2. Go back to `alt` for all icons
3. Use `alt` or `square` _just_ for these alternate social icons

???

cc: @Scotchester

**Comment by Scotchester** [comment]
Personally, I would follow [Font Awesome's lead](http://fontawesome.io/whats-new/) and use `-square`.

**Comment by himedlooff** [comment]
I was just going to say that `-square` makes sense and could be used for any icon in the future that is squared. We're definitely using squared social media icons in FJ.
