### ISSUE TITLE
Icon display issues

### ISSUE THREAD

**Issue by ascott1** [cfpb/cf-icons#23]
See https://github.com/cfpb/design-manual/issues/132

I'm a bit exasperated by this whole endeavor. :weary:

**Comment by iuloshi** [comment]
Don't dispair!!

So I checked the cf-icons docs page on my phone and the minicons are rendering correctly! Was the minicon font somehow lost in translation between CF and the Design Manual?

**Comment by ascott1** [comment]
:cry:

**Comment by ascott1** [comment]
It looks like the referenced issue has been solved... but the feeling of exasperation remains.
