### ISSUE TITLE
Font Generator

### ISSUE THREAD

**Issue by Dnpizarro** [cfpb/cf-icons#25]
Thanks to the good work of @himedlooff, it seems that we now have a working solution to our font generator issue. Here are the new findings:
- Use FontSquirrel's [Webfont Generator](http://www.fontsquirrel.com/tools/webfont-generator) to generate the webfont version. 
- Since our glyphs are in the "Private Use Area" of the unicode, FontSquirrel's generator will subset the font and cut out the private use glyphs unless you tell it **not** to. 
- Go into the expert options and select "No subsetting".
- Generate webfont!

If you spot any bugs with this webfont generator, please post your findings.

**Comment by himedlooff** [comment]
I added the Font Squirrel generator config file in the repo (pending this pr https://github.com/cfpb/cf-icons/pull/26). If anyone needs to generate more font files just follow the settings in that file.

**Comment by himedlooff** [comment]
And the txt file is merged and located here: https://github.com/cfpb/cf-icons/blob/gh-pages/src/font-source/generator_config.txt

**Comment by himedlooff** [comment]
We should definitely document the process.

**Comment by ascott1** [comment]
+1

**Comment by Dnpizarro** [comment]
I agree. Where do you think the documentation should live? I'm thinking creating section in the readme under [cf-icons](https://github.com/cfpb/cf-icons).

**Comment by himedlooff** [comment]
Sounds like a good place to me!
