### ISSUE TITLE
the Start Here link in the Read.me leads to 404 page

### ISSUE THREAD

**Issue by ghost** [cfpb/cf-icons#29]
In the Read.me, there is a link labeled 'start here.' 
When I click on it, then I see a 404 page and not a content page.

**Comment by himedlooff** [comment]
Good catch, I'll fix it up thanks!

**Comment by ascott1** [comment]
Merged!

**Comment by himedlooff** [comment]
Thanks @Vineyards and @ascott1! :dancers:
