### ISSUE TITLE
Add IE7 support

### ISSUE THREAD

**Issue by ascott1** [cfpb/cf-icons#3]

**Comment by ascott1** [comment]
IE7 specific stylesheet is now integrated locally, but isn't working. I think this is related to the font file issue mentioned in #2. Once IE8 is working, I'll revisit.

**Comment by himedlooff** [comment]
This has been working for a while now, yay!

**Comment by himedlooff** [comment]
Although I'm not sure if it's because of the JS hack from https://github.com/cfpb/cf-icons/issues/2
