### ISSUE TITLE
Should we move the JS hack into this repo?

### ISSUE THREAD

**Issue by himedlooff** [cfpb/cf-icons#34]
There is a JS hack needed to get this working consistently in IE8, see: https://github.com/cfpb/cf-icons/issues/2

Currently the hack lives in [cf-component-demo](https://github.com/cfpb/cf-component-demo/blob/master/raw/index.jade#L43-L52). Seems like we should have it live here in this repo. Let's figure out how to make this happen.

**Comment by himedlooff** [comment]
@Scotchester it looks like we're not even using this in cfgov-refresh. @ascott1 and @contolini are you using this hack in OAH?

**Comment by contolini** [comment]
Hmmmmm I don't think we are. Did this problem magically fix itself? :smiley:

**Comment by himedlooff** [comment]
They're working on the docs page, which doesn't use the hack: http://cfpb.github.io/cf-icons/docs/

![image](https://cloud.githubusercontent.com/assets/1093373/4908600/9d499b7c-646b-11e4-8a53-c50639e86ab7.png)

**Comment by himedlooff** [comment]
By the way the docs look great in IE8 RIGHT!?

**Comment by KimberlyMunoz** [comment]
Closing this issue since it seems like none of the other cf repos are using the hack.
