### ISSUE TITLE
Adding an icon for history

### ISSUE THREAD

**Issue by KimberlyMunoz** [cfpb/cf-icons#38]
eRegs uses its own icon font and we want to move over to cf-icons. Right now we use this history icon for the Regulation Timeline, and there isn't a good replacement for it in cf-icons.

Any chance we can add this in the next release?

![history](https://cloud.githubusercontent.com/assets/1860176/6353361/e66a7eb8-bc16-11e4-8f18-e6572a4e7b00.png)

(I got an svg too)

**Comment by Scotchester** [comment]
Paging @Dnpizarro, who doesn't watch this repo :)

**Comment by KimberlyMunoz** [comment]
Closed in #43
