### ISSUE TITLE
Add icon for livestream

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cf-icons#39]
cfgov-refresh will be using a livestream icon in several locations:

![screen shot 2015-02-24 at 12 42 21 pm](https://cloud.githubusercontent.com/assets/704760/6355254/a66742c2-bc22-11e4-972f-a39d2fe5a2b7.png)

**Comment by KimberlyMunoz** [comment]
Hey Ans,

I noticed that this was already included in latest version of cf-icons. I don't know if you want to wait to close this issue until the changes hit this repo or check it out now.

**Comment by anselmbradford** [comment]
@KimberlyMunoz Cool thanks! I'll leave this issue open till it actually makes it into this repo, but we (team fj) may be able to preemptively use the font already where we need it.

**Comment by anselmbradford** [comment]
Fixed in https://github.com/cfpb/cf-icons/pull/43
