### ISSUE TITLE
Helper classes/mixins

### ISSUE THREAD

**Issue by ascott1** [cfpb/cf-icons#4]
Font Awesome includes a number of helper classes and/or Less mixins to aid styling the icons. Is this something we should include? If so, what would be useful?

cc: @contolini @himedlooff @Scotchester

**Comment by Scotchester** [comment]
I say why not?

This is related but maybe deserving of its own issue: Should we align our naming conventions more closely with FA? Specifically, for example, they use the `-round` suffix to put icons on a circular BG, whereas we use `-alt`.

**Comment by ascott1** [comment]
I'd say it makes sense to use `-round` in that case.

**Comment by ascott1** [comment]
Since we're not a direct fork of Font Awesome, is there a line that we cross if we copy all of the helper classes/mixins from their Less? What's the best way to give attribution in that case?

**Comment by Scotchester** [comment]
That's a good question. Their code is licensed under MIT, so we're free to incorporate any of it. I think conceptually it's similar to [cfpb-grunt-internal](https://github.com/cfpb/grunt-cfpb-internal), which acknowledges inspiration from the original on the README and describes it as a joint work in the TERMS. Doing those things would probably be enough, I think.

**Comment by contolini** [comment]
Copying is definitely permissible (even encouraged, I'd argue) so long as we dual license it as @Scotchester mentions.

**Comment by himedlooff** [comment]
The variables for each icon character code would be useful too. In cfgov-refresh we've made some patterns that automatically append icons but we have to use the crazy `\e004` code to do it. It'd be nicer if we could just use a variable like FA does.

**Comment by KimberlyMunoz** [comment]
Working on this.

It looks like the following things might be useful:
- Mixins for each icon character code
- [Animation helper classes for spinning and pulse](http://fortawesome.github.io/Font-Awesome/examples/#animated)
- [Helper classes for rotating and flipping icons](http://fortawesome.github.io/Font-Awesome/examples/#rotated-flipped)
- [Bordered icons](http://fortawesome.github.io/Font-Awesome/examples#bordered-pulled)

**Comment by ascott1** [comment]
Those would all be _super_ useful.

**Comment by KimberlyMunoz** [comment]
Almost done. 

Quick question: For the mixins for each icon character code, Font Awesome has a page that lists all the variables like this:

```
// variables.less
// --------------------------
@fa-var-volume-down: "\f027";
@fa-var-volume-off: "\f026";
@fa-var-volume-up: "\f028";
...
// icons.less
// --------------------------
.@{fa-css-prefix}-volume-off:before { content: @fa-var-volume-off; }
.@{fa-css-prefix}-volume-down:before { content: @fa-var-volume-down; }
.@{fa-css-prefix}-volume-up:before { content: @fa-var-volume-up; }

```

Would it make sense to adopt that approach and have two places to update when we add new icons, or to have the mix-in near the class where it will be used?

```
@cf-var-left: "\e000";
.@{cf-icon-prefix}-left {
    &:before  {     content: @cf-var-left; }
    .lt-ie8 & { .cf-icon-ie7(@cf-var-left); }
}

@cf-var-left-round: "\e001";
.@{cf-icon-prefix}-left-round {
    &:before  {     content: @cf-var-left-round; }
    .lt-ie8 & { .cf-icon-ie7(@cf-var-left-round); }
}
```

**Comment by Scotchester** [comment]
I don't think it's good to have them in two places. My vote would be to have them all together, and not next to the classes.
