### ISSUE TITLE
0.4.2 tagged as minor when it was a patch release

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cf-icons#44]
Looks like https://github.com/cfpb/cf-icons/releases/tag/0.4.2 was tagged as a minor release but [semver](http://semver.org/) incremented as a patch release. Worth doing anything about?

**Comment by Scotchester** [comment]
I think it probably should have actually been the 0.5.0 release, due to the addition of new functionality, but things are always a little fuzzy at the pre-1.0 stage. We could change the release description to call it a patch release, just so it's consistent with itself. I'll do that.

**Comment by Scotchester** [comment]
Done.
