### ISSUE TITLE
Color icons?

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cf-icons#46]
This is certainly not a priority, but I just wanted to note for reference this icon set I saw https://github.com/icons8/flat-color-icons that delivers the icons as SVG so colors can be included. Wouldn't it be sweet if cf-icons included an option for colors? Browser support is all evergreens plus IE9+ w/ hacks.

**Comment by jimmynotjim** [comment]
I'm definitely interested in SVG over a web-font. I believe @Scotchester has also mentioned something about this recently.

**Comment by himedlooff** [comment]
Sounds like it could open up a can of works on the design side since they'd have to set some standards around it. I'm also not psyched about the browser support and the bloated process that might be involved with backfilling.

I do think it's cool though.

**Comment by Scotchester** [comment]
Leaving aside the issue Mike identified of how our one-color icons would be colorized by the designers, there are pros and cons to both techniques. I'd love to have both of them available as options in our toolbox.

**Comment by jimmynotjim** [comment]
[Current coverage](http://caniuse.com/#search=svg) is actually pretty good and png fallbacks are simple.

**Comment by anselmbradford** [comment]
This brings up the idea of having a variable in https://github.com/cfpb/cf-core/blob/gh-pages/src/cf-vars.less or as an option in https://github.com/cfpb/generator-cf that was like `@ie-min-support` or similar, that would set the minimum support level needed for a project. Fallbacks and polyfills could then refer to that variable to determine whether it was necessary that they be included or not.
Just some thoughts, maybe that would get too tangled with conditional logic.
