### ISSUE TITLE
Look into moving expressions in ie8 icons for performance reasons

### ISSUE THREAD

**Issue by KimberlyMunoz** [cfpb/cf-icons#53]
https://developer.yahoo.com/blogs/ydn/high-performance-sites-rule-7-avoid-css-expressions-7202.html

**Comment by Scotchester** [comment]
Just to clarify, we only use `expression` in the rules for IE**7** and under. Still a significant concern?

**Comment by KimberlyMunoz** [comment]
Actually it isn't. Some performance guidelines have removed it as a concern because modern browsers don't support them so it really only impacts IE7 and below. If we get lots of cases of IE7 crashes in New Relic, we might want to reevaluate.
